### ISSUE TITLE
Font not imported when deployed on Github pages

### ISSUE THREAD

**Issue by PMassicotte** [gadenbuie/xaringanthemer#12]
Hi and thank you for this nice package.

I am working on a presentation: http://www.pmassicotte.com/greenedge2019/

I want to use `Roboto` font in my slide. Based on the documentation, I did this:

```r
library(xaringanthemer)
duo(
  code_font_family = "Fira Code",
  code_font_url    = "https://cdn.rawgit.com/tonsky/FiraCode/1.204/distr/fira_code.css",
  text_font_google = google_font("Roboto", "400", "400i", "600i", "700")
)
```

This works fine locally on my computer. However, the `Roboto` font do not show when deployed on Github page (see the link above).

Any ideas?

**Comment by gadenbuie** [comment]
Hmmm this is odd -- I'm seeing Roboto in your slide text when using the Github page link.

![image](https://user-images.githubusercontent.com/5420529/53572071-6332ed00-3b38-11e9-871a-a6f7d6254d91.png)

Do you have any browser extensions that might be blocking the request to Google Fonts? What does it look like for you?

**Comment by PMassicotte** [comment]
Humm strange, I see it now. I have not changed anything. Anyhow, thank you :)
