### ISSUE TITLE
write_extra_css() should be able to overwrite the created file

### ISSUE THREAD

**Issue by pat-s** [gadenbuie/xaringanthemer#17]
If not by default, at least as an option :) Just saw that my created CSS file is Inf long :open_mouth:

**Comment by gadenbuie** [comment]
Yeah that makes sense. It was intended to be called in conjunction with the style functions that *would* overwrite the main CSS file and then `write_extra_css()` would append to that. I can easily make `append` a parameter.

I'm curious, though. Do you mind sharing the slides where you used `write_css_extra()`? I'd love to see how you're using it.

**Comment by pat-s** [comment]
The source Rmd is [here](https://github.com/mlr-org/mlr3-learndrake/blob/3ca8e5710bfcb5aaa6f976b844336586fd2f779e/slides/drake/index.Rmd).

> It was intended to be called in conjunction with the style functions that would overwrite the main CSS file and then write_extra_css() would append to that.

As you can see I prefer writing to an external file. I call the whole chunk including the `xaringanthemer` functions by hand after I made changes to it.
The "main" CSS file is overwritten each time while the external `extra.css` is appended.
