### ISSUE TITLE
Documentation for arg background_position in `write_xaringan_theme` not clear

### ISSUE THREAD

**Issue by TrashBirdEcology** [gadenbuie/xaringanthemer#18]
Can you please clarify in (write_xaringan_theme.rd)[man/write_xaringan_theme.rd] how to specify argument __background_position__?  background-position in theme.css can take two values (%) per argument to specify vertical and horizontal position. 

However, when I specify:
`r  write_xaringan_theme(background-position = c(0,100))`
xaringan_themer.css returns with
`r background-position: 0;`

I am not sure what the solution is, otherwise I would submit a PR.

**Comment by gadenbuie** [comment]
Here are a few examples from the [Background Position section](https://pkg.garrickadenbuie.com/xaringanthemer/articles/css-help.html#background-position) from the `css-help` vignette.

```
background_position = "center"
background_position = "top"
background_position = "left"
background_position = "bottom"
background_position = "25% 75%" # X-value (from left) Y-value (from top)
background_position = "bottom 10px right 20px" # 10px from bottom, 20px from right
background_position = "top left 10px" # at top but adjusted left 10px
```

In general, all arguments to xarignanthemer style functions are CSS values in strings.

I'll leave this issue open so that I remember to clarify this in the documentation.

**Comment by TrashBirdEcology** [comment]
Great, thanks for that clarification.


Jessica L. Burnett

GitHub <http://github.com/trashbirdecology>
CV/Resume
<https://github.com/TrashBirdEcology/cv/blob/master/burnett_extendedCV.pdf>
ORC ID: 0000-0002-0896-5099 <https://orcid.org/0000-0002-0896-5099>

**Comment by gadenbuie** [comment]
I've removed the CSS help vignette but I've now documented (in #33) which arguments accept CSS property values and included a link to the [MDN Web Docs](https://developer.mozilla.org/en-US/) page describing the syntax for the property values.
