### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Northbreeze** [gadenbuie/xaringanthemer#23]
Hi,

I was trying to download the package but I got the below error.
Error: Failed to install 'xaringanthemer' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Nastaba/AppData/Local/Temp/RtmpU14CUW/file766451c75541/xaringanthemer_0.2.0.tar.gz’ had non-zero exit status

**Comment by gadenbuie** [comment]
Hi @Northbreeze were you able to install the package? If not, can you provide more information? If you can send the output from `devtools::session_info()` that might be helpful. Also, try installing from a new, clean R session. If you copy and paste the full install process output that might be helpful, too.

**Comment by gadenbuie** [comment]
I'm hoping this was an early warning about #32 but please re-open if not.
