### ISSUE TITLE
No highlighting of R code input and output

### ISSUE THREAD

**Issue by luca-scr** [gadenbuie/xaringanthemer#35]
I would like to remove any highlighting of R code input and output from slides. 
I tried to set `code_highlight_color` but with no effect.
How can this be obtained using xaringanthemer?

**Comment by gadenbuie** [comment]
To disable code highlighting you can use the [highlightLines](https://github.com/gnab/remark/wiki/Configuration#highlighting) configuration parameter of remarkjs.

I think if you set

```
nature:
  highlightLines: false
```

in the [xaringan output options](https://slides.yihui.org/xaringan/#29) that would disable syntax highlighting.

**Comment by luca-scr** [comment]
Thanks for your reply, but likely I was not clear on my question. 

In the YAML preamble I have 
```
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
```
then I use xaringan-themer as follows
```
library(xaringanthemer)
style_mono_accent(
  base_color = "#5d81ab",
  inverse_background_color = "#3B4252",
  header_font_google = google_font("Fira Sans"),
  text_font_google   = google_font("Roboto"),
  code_font_google   = google_font("Fira Code"),
  base_font_size = "20px", 
  text_font_size = "1rem", 
  code_font_size = "0.7rem",
  header_h1_font_size = "1.5rem", 
  header_h2_font_size = "1.3rem", 
  header_h3_font_size = "1.15rem",
  code_highlight_color = "#272822",
  code_inline_color = "#000000",
  code_inline_font_size = "0.9rem"
)
```

The R code & output looks like the following screenshot.
![Screenshot 2020-06-17 at 17 24 04](https://user-images.githubusercontent.com/11585946/84917395-913a9880-b0bf-11ea-8aaa-aabc25f7bb24.png)

I would like to have all R code & output written in black (also comments is fine), so no syntax highlighting at all.

**Comment by gadenbuie** [comment]
Sorry, I meant to say to use the `highlightStyle` remarkjs parameter. Setting `highlightStyle: false` will turn of syntax highlight entirely.

```yaml
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      highlightStyle: false
```
