### ISSUE TITLE
Add `text_bold_font_weight` argument

### ISSUE THREAD

**Issue by matiasandina** [gadenbuie/xaringanthemer#50]
I'm not sure this is a bug, I'm doing something wrong, or Firefox is not rendering content properly.
I am following the example in the website documentation using `style_mono_accent()`.

```
style_mono_accent( 
  base_color = "#262626", #1c5253
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", 
                                   "300", "700", "300i")
```

Generates this .css

```
body {
  font-family: var(--text-font-family), var(--text-font-family-fallback), var(--text-font-base);
  font-weight: 300;
  color: var(--text-color);
}
```

This displays properly on the Rstudio viewer, but not on Firefox. The `strong` tag is overwritten by `font-weight: 300` in `body`.
The only way I found to have this display properly in Firefox is by adding "inherit" at the beginning of the weights on `google_font()`

```
style_mono_accent( 
  base_color = "#262626", #1c5253
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "inherit", 
                                   "300", "700", "300i")
```

Generates this .css

```
body {
  font-family: var(--text-font-family), var(--text-font-family-fallback), var(--text-font-base);
  font-weight: inherit;
  color: var(--text-color);
}
```

**Comment by gadenbuie** [comment]
Yeah, the first font weight in the list becomes the default font-weight of the `body`:

https://github.com/gadenbuie/xaringanthemer/blob/c1513bb8fdc2485461b0c82c5421fbaadee05a84/inst/scripts/style_xaringan_body.R#L88-L92

Try using this:

```r
style_mono_accent( 
  base_color = "#262626", #1c5253
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "700", "300i"), 
  extra_css = list(strong = list("font-weight" = 700))
)
```

**Comment by gadenbuie** [comment]
The real problem is that `font-weight` isn't explicitly set on `<strong>` by the xaringanthemer css. Some browsers provide a default value of for this tag and others don't, which is why you see a difference between RStudio's viewer and other browsers.

**Comment by matiasandina** [comment]
Do you think it makes sense to show this on the documentation? Maybe in the "Colors" section here https://pkg.garrickadenbuie.com/xaringanthemer/articles/xaringanthemer.html ?

**Comment by gadenbuie** [comment]
Not really. If anything, I could add a CSS rule to set the `font-weight` of `<strong>` to `bold`. That parameter could be tied to an R argument, like `text_bold_weight`, that would work like `text_font_weight`.

**Comment by matiasandina** [comment]
That would be great!
